# -*- coding: utf-8 -*-
"""EE016_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FeiSw3M3LGMHCz6VHwIB9DGtzE2f6wub
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler

# Load dataset
file_path = "/content/LD2011_2014.txt"
df = pd.read_csv(
    file_path,
    sep=';',
    index_col=0,
    decimal=',',
    quotechar='"',
    low_memory=False
)
df.index = pd.to_datetime(df.index)
# DATASET SIZE (Total samples and features)
# df.shape returns:
#   - Number of rows  = total time-stamped samples (140,256)
#   - Number of columns = total features (370 individual electricity readings)

print("Dataset shape:", df.shape)

# KEY VARIABLES AND THEIR MEANINGS
# Index: Timestamp (datetime)
#   - Represents when each measurement was recorded (every 15 minutes).
#
# Columns: MT_001 -> MT_370
#   - Each column corresponds to a different consumer.
#   - Values represent electricity load (in kW) at that timestamp.

# Randomly select 37 meters (10% of 370)
# doing al 370 columns is toooooo big. decreased sample size to just 10% for better readability
np.random.seed(42)
sample_meters = np.random.choice(df.columns, size=37, replace=False)

# Plot representative time series
plt.figure(figsize=(20,8))
for col in sample_meters:
    plt.plot(df.index[:1000], df[col][:1000], label=col, alpha=0.7)

plt.xlabel("Timestamp")
plt.ylabel("Electricity Load (kW)")
plt.title("Representative Electricity Load Time-Series (37 Random Clients)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Feature scaling (for neural network)
scaler = StandardScaler()
numeric_cols = df.select_dtypes(include='number').columns
df_scaled = df.copy()
df_scaled[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# Plot scaled time series
plt.figure(figsize=(20,8))
for col in sample_meters:
    plt.plot(df_scaled.index[:1000], df_scaled[col][:1000], alpha=0.7)

plt.xlabel("Timestamp")
plt.ylabel("Scaled Electricity Load")
plt.title("Representative Electricity Load Time-Series (Scaled Values)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()